import { Product } from './types';

export const catalog: Product[] = [
  {
    id: 'p001', slug: 'voltura-strada-sr', name: 'Voltura Strada SR', brand: 'Voltura',
    category: 'bike', discipline: 'road', level: 'expert', season: 'all',
    price: 4299, stock: 6,
    description: 'Bicicleta de carretera de carbono con grupo Shimano Ultegra Di2 de 12 velocidades.',
    specs: { frame: 'Carbono T800', groupset: 'Shimano Ultegra Di2 R8170', wheels: 'Voltura Aero45', weight: '7.6 kg' },
    sizes: ['48','50','52','54','56','58'],
    image: 'https://source.unsplash.com/600x400/?road+bike+cycling&sig=1',
    tags: ['carretera','race','di2','carbono','aero','shimano','ultegra'],
  },
  {
    id: 'p002', slug: 'voltura-strada-comp', name: 'Voltura Strada Comp', brand: 'Voltura',
    category: 'bike', discipline: 'road', level: 'beginner', season: 'all',
    price: 1199, stock: 14,
    description: 'Bicicleta de carretera de aluminio con grupo Shimano Tiagra, perfecta para iniciarse.',
    specs: { frame: 'Aluminio 6061', groupset: 'Shimano Tiagra 4700', wheels: 'Voltura R20', weight: '9.2 kg' },
    sizes: ['48','50','52','54','56','58'],
    image: 'https://source.unsplash.com/600x400/?road+bike+cycling&sig=2',
    tags: ['carretera','aluminio','entry','tiagra','shimano','iniciacion'],
  },
  {
    id: 'p003', slug: 'apex-aero-7', name: 'Apex Velo Aero 7', brand: 'Apex Velo',
    category: 'bike', discipline: 'road', level: 'expert', season: 'all',
    price: 5499, originalPrice: 5999, stock: 3,
    description: 'Aero de carretera con grupo electrónico SRAM Force AXS y ruedas perfil 50mm.',
    specs: { frame: 'Carbono Aero', groupset: 'SRAM Force AXS', wheels: 'Apex Aero50', weight: '7.8 kg' },
    sizes: ['50','52','54','56','58'],
    image: 'https://source.unsplash.com/600x400/?road+bike+cycling&sig=3',
    tags: ['carretera','aero','sram','axs','electronico','race','carbono'],
  },
  {
    id: 'p004', slug: 'apex-climber', name: 'Apex Velo Climber', brand: 'Apex Velo',
    category: 'bike', discipline: 'road', level: 'expert', season: 'all',
    price: 7999, stock: 2,
    description: 'Escaladora ultraligera con Dura-Ace Di2 y ruedas de perfil bajo para puertos.',
    specs: { frame: 'Carbono ultraligero', groupset: 'Shimano Dura-Ace Di2 R9270', wheels: 'Apex Climb33', weight: '6.8 kg' },
    sizes: ['50','52','54','56'],
    image: 'https://source.unsplash.com/600x400/?road+bike+cycling&sig=4',
    tags: ['carretera','escaladora','dura-ace','di2','shimano','ligera','race','puertos'],
    isNew: true,
  },
  {
    id: 'p005', slug: 'stratos-allure-disc', name: 'Stratos Allure Disc', brand: 'Stratoscycle',
    category: 'bike', discipline: 'road', level: 'intermediate', season: 'all',
    price: 2599, stock: 9,
    description: 'Endurance de carretera con freno de disco y grupo 105 Di2 para largas distancias.',
    specs: { frame: 'Carbono Endurance', groupset: 'Shimano 105 Di2 R7170', wheels: 'Stratos Endurance', weight: '8.3 kg' },
    sizes: ['50','52','54','56','58'],
    image: 'https://source.unsplash.com/600x400/?road+bike+cycling&sig=5',
    tags: ['carretera','endurance','105','di2','shimano','disco','gran-fondo'],
  },
  {
    id: 'p006', slug: 'ridge-tr1-pro', name: 'RidgeCarbon TR1 Pro', brand: 'RidgeCarbon',
    category: 'bike', discipline: 'road', level: 'expert', season: 'spring-summer',
    price: 6299, stock: 2,
    description: 'Bicicleta de contrarreloj y triatlón con geometría aero extrema.',
    specs: { frame: 'Carbono Aero TT', groupset: 'SRAM Red AXS', wheels: 'Ridge TT80', weight: '8.1 kg' },
    sizes: ['M','L','XL'],
    image: 'https://source.unsplash.com/600x400/?road+bike+cycling&sig=6',
    tags: ['triatlon','contrarreloj','tt','aero','sram','red','race'],
  },
  {
    id: 'p007', slug: 'ridge-sentinel-xc', name: 'RidgeCarbon Sentinel XC', brand: 'RidgeCarbon',
    category: 'bike', discipline: 'mtb', level: 'expert', season: 'all',
    price: 3799, stock: 5,
    description: 'MTB cross country rígida de carbono con grupo SRAM GX Eagle y horquilla 100mm.',
    specs: { frame: 'Carbono XC', groupset: 'SRAM GX Eagle 12v', fork: 'RockShox SID 100mm', wheels: '29"' },
    sizes: ['S','M','L','XL'],
    image: 'https://source.unsplash.com/600x400/?mountain+bike+trail&sig=7',
    tags: ['mtb','xc','cross-country','hardtail','rigida','carbono','sram','gx','29'],
  },
  {
    id: 'p008', slug: 'ridge-vector-fs', name: 'RidgeCarbon Vector FS', brand: 'RidgeCarbon',
    category: 'bike', discipline: 'mtb', level: 'intermediate', season: 'all',
    price: 4499, stock: 4,
    description: 'MTB trail de doble suspensión 140mm con grupo Shimano XT 12v.',
    specs: { frame: 'Carbono Trail', groupset: 'Shimano XT M8100', travel: '140mm', wheels: '29"' },
    sizes: ['S','M','L','XL'],
    image: 'https://source.unsplash.com/600x400/?mountain+bike+trail&sig=8',
    tags: ['mtb','trail','doble-suspension','full-suspension','shimano','xt','140mm','29'],
  },
  {
    id: 'p009', slug: 'voltura-backwoods', name: 'Voltura Backwoods Enduro', brand: 'Voltura',
    category: 'bike', discipline: 'mtb', level: 'expert', season: 'all',
    price: 5299, stock: 3,
    description: 'MTB enduro con 170mm de recorrido y grupo SRAM X01 Eagle para descensos exigentes.',
    specs: { frame: 'Carbono Enduro', groupset: 'SRAM X01 Eagle', travel: '170mm', wheels: 'Mixed (29/27.5)' },
    sizes: ['S','M','L','XL'],
    image: 'https://source.unsplash.com/600x400/?mountain+bike+trail&sig=9',
    tags: ['mtb','enduro','dh','descenso','sram','x01','170mm','mullet'],
  },
  {
    id: 'p010', slug: 'apex-roam-29', name: 'Apex Velo Roam 29', brand: 'Apex Velo',
    category: 'bike', discipline: 'mtb', level: 'beginner', season: 'all',
    price: 999, stock: 18,
    description: 'MTB hardtail de aluminio con ruedas 29" para iniciarse en la montaña.',
    specs: { frame: 'Aluminio 6061', groupset: 'Shimano Deore 12v', fork: 'Suntour XCM 100mm', wheels: '29"' },
    sizes: ['S','M','L','XL'],
    image: 'https://source.unsplash.com/600x400/?mountain+bike+trail&sig=10',
    tags: ['mtb','hardtail','aluminio','entry','iniciacion','deore','29','shimano'],
  },
  {
    id: 'p011', slug: 'ridge-apex-ews', name: 'RidgeCarbon Apex EWS', brand: 'RidgeCarbon',
    category: 'bike', discipline: 'mtb', level: 'expert', season: 'all',
    price: 7299, stock: 2,
    description: 'MTB enduro de alta gama, edición competición EWS, doble suspensión 165mm.',
    specs: { frame: 'Carbono Race Enduro', groupset: 'SRAM XX1 AXS', travel: '165mm', wheels: '29"' },
    sizes: ['M','L','XL'],
    image: 'https://source.unsplash.com/600x400/?mountain+bike+trail&sig=11',
    tags: ['mtb','enduro','race','ews','sram','xx1','axs','race','carbono'],
    isNew: true,
  },
  {
    id: 'p012', slug: 'stratos-gravelpath', name: 'Stratos Gravelpath', brand: 'Stratoscycle',
    category: 'bike', discipline: 'gravel', level: 'intermediate', season: 'all',
    price: 2299, stock: 7,
    description: 'Gravel de acero con grupo Shimano GRX, perfecto para aventuras de largo recorrido.',
    specs: { frame: 'Acero Reynolds 853', groupset: 'Shimano GRX RX810', wheels: '700c tubeless ready', weight: '10.1 kg' },
    sizes: ['50','53','55','57','60'],
    image: 'https://source.unsplash.com/600x400/?gravel+bike+adventure&sig=12',
    tags: ['gravel','acero','grx','shimano','bikepacking','aventura','tubeless'],
  },
  {
    id: 'p013', slug: 'voltura-crossfire', name: 'Voltura Crossfire', brand: 'Voltura',
    category: 'bike', discipline: 'gravel', level: 'expert', season: 'all',
    price: 3899, stock: 4,
    description: 'Gravel de carbono con grupo SRAM Rival AXS y geometría race para gravel competitivo.',
    specs: { frame: 'Carbono Gravel', groupset: 'SRAM Rival AXS', wheels: 'Voltura GR40', weight: '8.4 kg' },
    sizes: ['50','52','54','56','58'],
    image: 'https://source.unsplash.com/600x400/?gravel+bike+adventure&sig=13',
    tags: ['gravel','carbono','sram','rival','axs','race','competicion'],
  },
  {
    id: 'p014', slug: 'apex-allroad', name: 'Apex Velo Allroad', brand: 'Apex Velo',
    category: 'bike', discipline: 'gravel', level: 'beginner', season: 'all',
    price: 1399, stock: 11,
    description: 'Gravel de aluminio polivalente, ideal para asfalto y caminos.',
    specs: { frame: 'Aluminio 6061', groupset: 'Shimano GRX 400 2x10', wheels: '700c', weight: '10.6 kg' },
    sizes: ['50','53','56','59'],
    image: 'https://source.unsplash.com/600x400/?gravel+bike+adventure&sig=14',
    tags: ['gravel','aluminio','entry','grx','shimano','polivalente'],
  },
  {
    id: 'p015', slug: 'velocore-aero55', name: 'VeloCore Aero55 Wheelset', brand: 'VeloCore',
    category: 'wheels', discipline: 'road', level: 'expert', season: 'all',
    price: 1899, originalPrice: 2199, stock: 8,
    description: 'Juego de ruedas de carbono perfil 55mm, optimizadas para etapas llanas y aero.',
    specs: { material: 'Carbono', profile: '55mm', weight: '1480g', hubs: 'VeloCore Pro', tubeless: 'Sí' },
    image: 'https://source.unsplash.com/600x400/?cycling+components+carbon&sig=15',
    tags: ['ruedas','wheelset','carbono','aero','55mm','carretera','tubeless'],
  },
  {
    id: 'p016', slug: 'velocore-climb38', name: 'VeloCore Climb38 Wheelset', brand: 'VeloCore',
    category: 'wheels', discipline: 'road', level: 'expert', season: 'all',
    price: 1599, stock: 6,
    description: 'Juego de ruedas de carbono perfil 38mm, ideales para escalada y polivalencia.',
    specs: { material: 'Carbono', profile: '38mm', weight: '1320g', hubs: 'VeloCore Pro', tubeless: 'Sí' },
    image: 'https://source.unsplash.com/600x400/?cycling+components+carbon&sig=16',
    tags: ['ruedas','wheelset','carbono','escalada','climb','38mm','carretera','ligeras'],
  },
  {
    id: 'p017', slug: 'voltura-pro-stem', name: 'Voltura Pro Stem 110', brand: 'Voltura',
    category: 'components', discipline: 'road', level: 'intermediate', season: 'all',
    price: 199, stock: 22,
    description: 'Potencia de carbono UD 110mm con ángulo -7°, peso 115g.',
    specs: { material: 'Carbono UD', length: '110mm', angle: '-7°', weight: '115g', clampDiameter: '31.8mm' },
    image: 'https://source.unsplash.com/600x400/?cycling+components+carbon&sig=17',
    tags: ['componentes','potencia','stem','carbono','manillar','110mm'],
  },
  {
    id: 'p018', slug: 'velocore-saddlex', name: 'VeloCore SaddleX Carbon', brand: 'VeloCore',
    category: 'components', discipline: 'multi', level: 'expert', season: 'all',
    price: 279, stock: 15,
    description: 'Sillín de carbono con railes de carbono, peso 145g, anchura 142mm.',
    specs: { shell: 'Carbono', rails: 'Carbono', weight: '145g', width: '142mm' },
    image: 'https://source.unsplash.com/600x400/?cycling+components+carbon&sig=18',
    tags: ['componentes','sillin','saddle','carbono','race','ligero'],
  },
  {
    id: 'p019', slug: 'helix-prorace-jersey', name: 'HelixWear ProRace Jersey', brand: 'HelixWear',
    category: 'apparel', discipline: 'road', level: 'expert', season: 'spring-summer',
    price: 119, stock: 30,
    description: 'Maillot de competición de manga corta, tejido aero y ligero, corte race.',
    specs: { fit: 'Race', material: 'Aero Lite', sleeves: 'Manga corta', pockets: '3 traseros' },
    sizes: ['XS','S','M','L','XL','XXL'],
    image: 'https://source.unsplash.com/600x400/?cycling+jersey+kit&sig=19',
    tags: ['ropa','maillot','jersey','manga-corta','verano','competicion','race','aero'],
  },
  {
    id: 'p020', slug: 'helix-endurance-bib', name: 'HelixWear Endurance Bib', brand: 'HelixWear',
    category: 'apparel', discipline: 'road', level: 'intermediate', season: 'spring-summer',
    price: 159, stock: 25,
    description: 'Culotte largo con tirantes y badana de alta densidad para 6h+ sobre la bici.',
    specs: { fit: 'Endurance', chamois: 'Pro 4h+', length: 'Largo', material: 'Lycra italiana' },
    sizes: ['XS','S','M','L','XL','XXL'],
    image: 'https://source.unsplash.com/600x400/?cycling+jersey+kit&sig=20',
    tags: ['ropa','culotte','bib-short','bib','tirantes','verano','endurance','gran-fondo'],
  },
  {
    id: 'p021', slug: 'helix-thermoline-jacket', name: 'HelixWear ThermoLine Jacket', brand: 'HelixWear',
    category: 'apparel', discipline: 'multi', level: 'intermediate', season: 'fall-winter',
    price: 189, stock: 12,
    description: 'Chaqueta térmica cortavientos para entrenamiento en invierno, transpirable.',
    specs: { fit: 'Regular', material: 'Softshell térmico', windproof: 'Sí', waterRepellent: 'DWR' },
    sizes: ['S','M','L','XL','XXL'],
    image: 'https://source.unsplash.com/600x400/?cycling+jersey+kit&sig=21',
    tags: ['ropa','chaqueta','termica','invierno','cortavientos','jacket','fall-winter'],
  },
  {
    id: 'p022', slug: 'helix-sr-carbon-shoes', name: 'HelixWear SR Carbon Shoes', brand: 'HelixWear',
    category: 'apparel', discipline: 'road', level: 'expert', season: 'all',
    price: 299, stock: 16,
    description: 'Zapatillas de carretera con suela de carbono y cierre BOA Li2 doble.',
    specs: { sole: 'Carbono SR3', closure: 'BOA Li2 x2', weight: '230g', cleatType: '3 tornillos' },
    sizes: ['39','40','41','42','43','44','45','46'],
    image: 'https://source.unsplash.com/600x400/?cycling+jersey+kit&sig=22',
    tags: ['ropa','zapatillas','shoes','carretera','carbono','boa','race'],
  },
  {
    id: 'p023', slug: 'nivox-proshield', name: 'Nivox Optics ProShield', brand: 'Nivox',
    category: 'accessories', discipline: 'multi', level: 'intermediate', season: 'all',
    price: 159, stock: 28,
    description: 'Gafas de sol de ciclismo con lente fotocromática y campo de visión amplio.',
    specs: { lens: 'Fotocromática', category: '1-3', frame: 'TR90', weight: '32g' },
    image: 'https://source.unsplash.com/600x400/?cycling+accessories&sig=23',
    tags: ['accesorios','gafas','sunglasses','fotocromaticas','proteccion'],
  },
  {
    id: 'p024', slug: 'velocore-lumenmax-1200', name: 'VeloCore LumenMax 1200', brand: 'VeloCore',
    category: 'accessories', discipline: 'multi', level: 'intermediate', season: 'fall-winter',
    price: 89, stock: 35,
    description: 'Luz frontal recargable USB-C de 1200 lúmenes, autonomía hasta 12h.',
    specs: { lumens: '1200', battery: '4000mAh', charging: 'USB-C', runtime: '2h max / 12h eco' },
    image: 'https://source.unsplash.com/600x400/?cycling+accessories&sig=24',
    tags: ['accesorios','luz','luces','frontal','iluminacion','invierno','usb-c'],
  },
  {
    id: 'p025', slug: 'velocore-pulse-gps', name: 'VeloCore Pulse GPS', brand: 'VeloCore',
    category: 'accessories', discipline: 'multi', level: 'intermediate', season: 'all',
    price: 349, originalPrice: 399, stock: 14,
    description: 'Ciclocomputador GPS con mapas, navegación y conectividad ANT+/Bluetooth.',
    specs: { display: '2.7" color', battery: '20h GPS', connectivity: 'ANT+/BT', maps: 'Incluidos Europa' },
    image: 'https://source.unsplash.com/600x400/?cycling+accessories&sig=25',
    tags: ['accesorios','gps','ciclocomputador','navegacion','sensores','ant'],
  },
];
